---
- hosts: build
  vars_prompt:
   - name: version
     prompt: "Ckan Version"
     private: False
   - name: iteration
     prompt: "Iteration"
     private: False
   - name: datapusher
     prompt: "Enable datapusher (y/n)?"
     default: "y"
     private: false
  tasks:
   - name: install epel
      action: command creates=/etc/yum.repos.d/epel.repo rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
    - name: make sure packages are installed
      action: yum pkg=$item state=installed
      with_items:
        - htop
        - rubygems
        - python-virtualenv
        - python-setuptools
        - git
        - python-devel
        - ruby-devel
        - postgresql
        - postgresql-libs
        - postgresql-devel
        - libxml2-devel
        - libxslt-devel
        - httpd
        - rpmdevtools
        - gcc
        - gcc-c++
        - make
        - bison
        - createrepo
        - mod_wsgi
        - tomcat6
        - cronie
        - libselinux-python

    - name: install fpm
      action: command gem install -v 0.4.21 fpm creates=/usr/local/bin/fpm

    - name: delete old directories
      action: file path={{ item }} state=absent
      with_items:
        - /etc/ckan
        - /usr/lib/ckan

    - name: pull ckan version
      action: git repo=https://github.com/okfn/ckan dest=/usr/lib/ckan/default/src/ckan version=release-v{{ version }}

    - name: get pip
      action: easy_install name=pip
   
   - name: install requirements and make virtualenv
      action: pip requirements=/usr/lib/ckan/default/src/ckan/pip-requirements.txt virtualenv=/usr/lib/ckan/default/ virtualenv_site_packages=yes

    - name: run setup.py develop for ckan
      action: command chdir=/usr/lib/ckan/default/src/ckan/ ../../bin/python setup.py develop

      # if datapusher needs to be setup
    - name: install ckanserviceprovider and make virtualenv for datapusher
      action: pip virtualenv=/usr/lib/ckan/datapusher/ virtualenv_site_packages=no name='git+https://github.com/okfn/ckan-service-provider#egg=ckanserviceprovider'
      when: datapusher == 'y'

    - name: pull datapusher
      action: git dest=/usr/lib/ckan/datapusher/src/datapusher repo=https://github.com/okfn/datapusher
      when: datapusher == 'y'

    - name: run setup.py develop for datapusher
      action: command chdir=/usr/lib/ckan/datapusher/src/datapusher/ ../../bin/python setup.py develop
      when: datapusher == 'y'

    - name: create directories
      action: file path={{ item }} state=directory
      with_items:
        - /etc/ckan/default
        - /var/www/build

    - name: copy all needed files
      action: copy src={{ item }} dest=/{{ item }}
      with_items:
        - etc/ckan/default/who.ini
        - etc/ckan/default/apache.wsgi
        - etc/apache2/sites-available/ckan_default
        - etc/nginx/sites-available/ckan
        - etc/cron.daily/remove_old_sessions

    - name: copy executables
      action: copy src={{ item }} dest=/{{ item }} mode=744
      with_items:
        - usr/bin/ckan

    - name: template the after web script
      action: template src=tmp/after_web.j2 dest=/tmp/after_web.sh mode=744

    - name: build deb main
      action: command chdir=/var/www/build fpm
              -t deb -s dir
              --name python-ckan
              --description='CKAN is an open-source DMS (data management system) for powering data hubs and data portals.'
              --license='AGPL v3.0'
              --maintainer='CKAN team <ckan-dev@lists.okfn.org>'
              --vendor='Open Knowledge Foundation'
              --url='http://ckan.org'
              --after-install=/tmp/after_web.sh
              --iteration {{ iteration }}
              --version {{ version }}
              --depends nginx --depends apache2 --depends libapache2-mod-wsgi --depends libpq5
              --config-files /etc/apache2/sites-available/ckan_default --config-files /etc/nginx/sites-available/ckan
              /usr/lib/ckan/ /etc/ckan/ /usr/bin/ckan /etc/cron.daily/remove_old_sessions /etc/apache2/sites-available/ckan_default /etc/nginx/sites-available/ckan
